### PR TITLE
Youtube integration

### PR DESCRIPTION
**Pull request by saharki**
#52

### CODE REVIEW

**Comment by saharki** [comment]
@yotamberk I have assigned you as UI developer on this matter

**Comment by saharki** [comment]
@yotamberk Exporter is done. 
Style it as you pleased :)

**Comment by yotamberk** [comment]
> @yotamberk I have assigned you as UI developer on this matter

I'll be glad too. But NOHOMO

**Comment by saharki** [comment]
@yotamberk Approve this PR if you think it's ready.

**Pull request merged**
